export const Action = {
  GET_TODOS: "GET_TODOS",
  UPDATE_TRIGGER: 'UPDATE_TRIGGER',
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  VIEW_PRODUCT: 'VIEW_PRODUCT',
  LOADING: 'LOADING',

};
